### ISSUE TITLE
Future updates to matrixStats may break your package tests

### ISSUE THREAD

**Issue by HenrikBengtsson** [MartinLoza/Canek#12]
Hi,

we're discussing updating **matrixStats** such that `rowMedians()` uses `useNames = TRUE` by default.  When/if that happens, reverse-package dependency checks show that **Carek** will break (https://github.com/HenrikBengtsson/matrixStats/issues/227).  Specifically, it'll give:

```
─  checking tests ...
   Running the tests in ‘tests/testthat.R’ failed.
   Last 13 lines of output:
     > library(testthat)
     > library(Canek)
     > 
     > test_check("Canek")
     [ FAIL 1 | WARN 0 | SKIP 0 | PASS 89 ]
     
     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Failure ('test-Estimation.R:29:3'): Median Method ───────────────────────────
     y$`Correction Vector`[1] not equal to 0.00523153.
     names for target but not for current
     
     [ FAIL 1 | WARN 0 | SKIP 0 | PASS 89 ]
     Error: Test failures
     Execution halted
```

This can be fixed by relaxing that test to no consider the `names` attribute.  I've created https://github.com/MartinLoza/Canek/pull/11 to fix this - it's a very simply update.

It would be great if you could merge this for your next release.  Thanks.

**Comment by ddiez** [comment]
Thank you @HenrikBengtsson for the news and the fix. PR merged.
