### ISSUE TITLE
CRAN update?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MartinLoza/Canek#16]
Hello. Would you mind submitting the updated version of **Canek** that addresses #12 to CRAN?  This would prevent it from break when **matrixStats** moves to `useNames = TRUE`.

**Comment by MartinLoza** [comment]
Hi Henrik, 
The new version is now available in CRAN, thank you for the suggestion and issue!

**Comment by HenrikBengtsson** [comment]
Thank you. I've just verified that Cranek 0.2.2 passes all revdep checks for matrixStats.
