### ISSUE TITLE
Output of cluster_louvain() will change with next igraph

### ISSUE THREAD

**Issue by szhorvat** [MartinLoza/Canek#24]
I'm writing to let you know about an upcoming change in igraph that causes one of the Canek tests to fail.

The following test relies on `cluster_louvain()` producing the same result for the same seed even across igraph versions:

https://github.com/MartinLoza/Canek/blob/master/tests/testthat/test-Clustering.R

We do not guarantee that the output of such stochastic functions won't change across versions. The only guarantee is that the statistical properties of the result stay the same. In fact, in an upcoming version of igraph, `cluster_louvain()` will change, causing this test in Canek to fail.

Can you please update the test so that it would not depend on a specific output?

**Comment by krlmlr** [comment]
We're releasing igraph 2.0.0 just before CRAN closes for Christmas. Tracking issue: https://github.com/igraph/rigraph/issues/989.

**Comment by krlmlr** [comment]
Thanks for the quick fix!

**Comment by MartinLoza** [comment]
@krlmlr @szhorvat, you are welcome. Thank you for the notice!
