### ISSUE TITLE
Test suite will break with the upcoming version of igraph 1.3.0

### ISSUE THREAD

**Issue by ntamas** [MartinLoza/Canek#7]
The test suite will break after the release of the next version of `igraph` (1.3.0) due to a change in the `cluster_louvain` function, which now has a stochastic implementation (details in PR https://github.com/igraph/igraph/pull/1696). Hence, the hardcoded result in the unit test (`test-Clustering.R`) is no longer exactly the same although it is still valid. Also, note that the RNG is seeded _outside_ the test case, which means that the result can potentially be dependent on the execution of the order of the unit tests.

In order to get reproducible results, you should seed the RNG directly prior to running the clustering. Note that even with  seeding, we cannot guarantee that the result will stay exactly the same in upcoming versions of igraph as it may also depend on the internal organization of the code within the C core of igraph. I'd advise testing whether the modularity or some other related measure of the obtained clustering falls within certain bounds instead of hardcoding the expected clustering in the unit test.

**Comment by MartinLoza** [comment]
Thanks for the notice. Fixed in the latest version.
